/*properties([
    parameters([
        [$class: 'ChoiceParameter', 
            choiceType: 'PT_MULTI_SELECT', 
            description: 'Select the Env Name from the Dropdown List', 
            filterLength: 1, 
            filterable: false, 
            name: 'environment', 
            randomName: 'choice-parameter-5631314439613978', 
            script: [
                $class: 'GroovyScript', 
                fallbackScript: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        'return[\'Could not get Env\']'
                ], 
                script: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        'return["Dev","Test","Prod"]'
                ]
            ]
        ], 
        [$class: 'CascadeChoiceParameter', 
            choiceType: 'PT_MULTI_SELECT', 
            description: 'Select the Server from the Dropdown List', 
            filterLength: 1, 
            filterable: false, 
            name: 'server', 
            randomName: 'choice-parameter-5631314456178619', 
            referencedParameters: 'environment', 
            script: [
                $class: 'GroovyScript', 
                fallbackScript: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        'return[\'Could not get Environment from Env Param\']'
                ], 
                script: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        ''' if (environment.equals("Dev")){
                                return["Dev1","Dev2","Dev3"]
                            }
                            else if(environment.equals("Test")){
                                return["Test1","Test2","Test3"]
                            }
                            else if(environment.equals("Prod")){
                                return["Prod1","Prod2","Prod3"]
                            }
                        '''
                ]
            ]
        ],

        choice(name: 'script',
        choices: 'DumpFileCleanup',
        description: 'Select script:'),

        string(name: 'TargetPath', description: 'File(s) you want to review:'),
        string(name: 'ErrorCode', description: 'Error to search for:'),
        string(name: 'OutputSummary', description: 'Path to place review:')
    ])
])
*/

def String[] serverGroup = "${params.server}".split(',');

// Create the pipeline
pipeline {
    // Allows pipeline to be run on any available agent
    agent any
    // Stages in build pipeline
    stages {
        // First stage in pipeline: review inputs and output to Jenkins console
        stage ('Parameter Validation') {
        // Steps in Parameter Validation stage
            steps {
                // Output parameters selected at time of build to Jenkins console
                echo '---------------------------------------------------------'
                echo "Checking tool input... selected: ${params.tool}"
                echo "Checking environment input... selected: ${params.environment}"
                echo "Checking region input... selected: ${params.region}"
                echo "Checking server input(s)... selected: ${params.server}"
                echo "Checking error input... selected: ${params.errorCode}"
                echo '---------------------------------------------------------'
            }
        }
        // Second stage in pipeline: download script and execute on in-scope servers
        stage ('Execute Script') {
            steps {
                script {
                    // For Loop to utilize the serverGroup array 
                    for (x in serverGroup) { 
                        // Output each server to console with line for spacing
                        echo "$x ---------------------------------------------------------\n"

                        echo "The script execution in this block is to review logs with error code ${params.ErrorCode} in the ${params.environment} environment and ${params.region} region on the $x server."
                        // Where the script will be executed
                        node(label: "$x") {
                            // Checkout scripts from remote repo and download to Jenkins master 
                            git (
                                [url: 'https://github.com/tylersul/jenkins-bax.git', 
                                branch: 'master'])
                            // Execute script on servers
                            script {
                                powershell(". '.\\SearchError.ps1'")
                            }
                        } 
                    }
                }
            }
        }
    }
}



