/**************** Variable Definition ****************/
// Create string array of user id's based on user input
def String[] idGroup = "${params.id}".split(',');

/**************** Pipeline Definition ****************/
pipeline {
    // Allows pipeline to run on any available node if not explicitly defined 
    agent any
    // Create separate stages in build pipeline
    stages {
        // Define first stage in pipeline: review user inputs and output to Jenkins console
        stage ('Parameter Validation') {
        // Define steps in the 'Parameter Validation' stage
            steps {
                script {
                    // Error handling - if any parameter is left blank, the build will automatically fail
                    if ("${params.project_code}" == '' || "${params.group}" == '' || "${params.action}" == '' || "${params.id}" == '') {
                        error("Build failed because a required parameter was not selected.\n  All available parameters in this pipeline are required.")
                    }
                }
                // Output parameters selected at time of build to Jenkins console
                echo '------------------------------------------------------------------------------------------------------------------'
                echo "Checking project code input... user selected: ${params.project_code}"
                echo "Checking group input(s)... user selected: ${params.group}"
                echo "Checking action input(s)... user selected: ${params.action}"
                echo "Checking id input(s)... user selected: ${params.id}"
                echo '------------------------------------------------------------------------------------------------------------------'
            }
        }
// Define second stage in pipeline: access NetApp and download file to local workspace
        stage ('Execute Script') {

            // Define steps in the 'Execute Script Stage'
            steps {

                // Script block to encapsulate three nested loops
                script {

                    // Loop through regions in the idGroup String Array
                    for (x in idGroup) {
                                                                            
                        // Two echos: one for spacing in the log and the other to detail what will occur in each block 
                        echo "$x --------------------------------------------------------------------------------------------------\n"
                        echo "The script execution in this block will ${params.action} $x in the ${params.group} group."

                        // Node label determines where the script will execute
                        node(label: "DEFRCOGAPP901") {
                            // Execute Windows Batch File - Change directory to NetApp file share and copy script to Jenkins workspace
                            bat """
                                pushd \\\\USOHNETCLU001_data_lif1.aws.baxter.com\\Cognos_Analytics_Prod
                                cd \\Administration\\Scripts
                                copy AccessChange.ps1 C:\\Jenkins\\workspace\\Baxter-Pipelines\\Access-Change
                                copy AccessChange.ps1 C:\\Jenkins\\workspace\\Baxter-Pipelines\\Access-Change@2
                                """
                            // Execute Powershell script
                            script {
                                powershell(". '.\\AccessChange.ps1 -ProjectCode ${params.project_code} -Group ${params.group} -AddRemove ${params.action} -User_id  $x'")
                            }
                        } 
                    }
                }
            }
        }
    }
}   