properties([
    parameters([
        [$class: 'ChoiceParameter', 
            choiceType: 'PT_SINGLE_SELECT', 
            description: 'Select the Env Name from the Dropdown List', 
            filterLength: 1, 
            filterable: false, 
            name: 'environment', 
            randomName: 'choice-parameter-5631314439613978', 
            script: [
                $class: 'GroovyScript', 
                fallbackScript: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        'return[\'Could not get Env\']'
                ], 
                script: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        'return["Dev","Test","Prod"]'
                ]
            ]
        ], 
        [$class: 'CascadeChoiceParameter', 
            choiceType: 'PT_SINGLE_SELECT', 
            description: 'Select the Server from the Dropdown List', 
            filterLength: 1, 
            filterable: false, 
            name: 'server', 
            randomName: 'choice-parameter-5631314456178619', 
            referencedParameters: 'environment', 
            script: [
                $class: 'GroovyScript', 
                fallbackScript: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        'return[\'Could not get Environment from Env Param\']'
                ], 
                script: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        ''' if (environment.equals("Dev")){
                                return["Dev1","Dev2","Dev3"]
                            }
                            else if(environment.equals("Test")){
                                return["Test1","Test2","Test3"]
                            }
                            else if(environment.equals("Prod")){
                                return["Prod1","Prod2","Prod3"]
                            }
                        '''
                ]
            ]
        ],
        choice(name: 'script',
        choices: 'DumpFileCleanup',
        description: 'Select script:'),

        string(name: 'SourcePath', description: 'File(s) you want to remove:'),
        string(name: 'OutputSummary', description: 'Path to place review:')
    ])
])

pipeline {
    agent any
    // stages in build pipeline
    stages {
        //first stage
        stage ('Parameter Validation') {
        //steps in test stage
            steps {
                echo 'Checking environment input:'
                echo "Selected: ${params.environment}"
                echo 'Checking server input:'
                echo "Selected: ${params.server}"
                echo 'Checking script input'
                echo "Selected: ${params.script}"
                echo 'Checking username input:'
                echo "Selected: ${params.WindowsUser}"
                echo 'Checking password:'
                echo "Selected: ${params.WindowsPassword}"
            }
        }
        stage ('Execute Script') {
            steps {
                script {
                    if ("${params.environment}" == 'Dev' && "${params.server}" == 'Dev1') {
                            echo "The script being executed next is ${params.script} in the ${params.environment} on the ${params.server} server."
                            node(label: 'Dev') {
                                git (
                                    [url: 'https://github.com/tylersul/jenkins-bax.git', 
                                    branch: 'master'])
                                script {
                                    powershell(". '.\\DeleteFiles.ps1'")
                                }
                            } 
                    }
                    if ("${params.environment}" == 'Dev' && "${params.server}" == 'Dev2') {
                            echo "The script being executed next is ${params.script} in the ${params.environment} on the ${params.server} server."
                            node(label: 'Dev') {
                                git (
                                    [url: 'https://github.com/tylersul/jenkins-bax.git', 
                                    branch: 'master'])
                                script {
                                    powershell(". '.\\DeleteFiles.ps1'")
                                }
                            } 
                    }
                    if ("${params.environment}" == 'Dev' && "${params.server}" == 'Dev3') {
                            echo "The script being executed next is ${params.script} in the ${params.environment} on the ${params.server} server."
                            node(label: 'Dev') {
                                git (
                                    [url: 'https://github.com/tylersul/jenkins-bax.git', 
                                    branch: 'master'])
                                script {
                                    powershell(". '.\\DeleteFiles.ps1'")
                                }
                            } 
                    } 
                    if ("${params.environment}" == 'Test' && "${params.server}" == 'Test1') {
                            echo "The script being executed next is ${params.script} in the ${params.environment} on the ${params.server} server."
                            node(label: 'Test') {
                                //git (
                                    //[url: 'https://github.com/tylersul/jenkins-bax.git', 
                                    //branch: 'master'])
                                //script {
                                    //powershell(". '.\\DeleteFiles.ps1'")
                                //}
                                zip zipFile: 'Test.zip', dir:'C:\\zipme'
                            } 
                    }
                    if ("${params.environment}" == 'Test' && "${params.server}" == 'Test2') {
                            echo "The script being executed next is ${params.script} in the ${params.environment} on the ${params.server} server."
                            node(label: 'Test') {
                                git (
                                    [url: 'https://github.com/tylersul/jenkins-bax.git', 
                                    branch: 'master'])
                                script {
                                    powershell(". '.\\DeleteFiles.ps1'")
                                }
                            } 
                    }
                    if ("${params.environment}" == 'Test' && "${params.server}" == 'Test3') {
                            echo "The script being executed next is ${params.script} in the ${params.environment} on the ${params.server} server."
                            node(label: 'Test') {
                                git (
                                    [url: 'https://github.com/tylersul/jenkins-bax.git', 
                                    branch: 'master'])
                                script {
                                    powershell(". '.\\DeleteFiles.ps1'")
                                }    
                            } 
                    }
                    if ("${params.environment}" == 'Prod' && "${params.server}" == 'Prod1') {
                            echo "The script being executed next is ${params.script} in the ${params.environment} on the ${params.server} server."
                            node(label: 'Prod') {
                                git (
                                    [url: 'https://github.com/tylersul/jenkins-bax.git', 
                                    branch: 'master'])
                                script {
                                    powershell(". '.\\DeleteFiles.ps1'")
                                }
                            } 
                    }
                    if ("${params.environment}" == 'Prod' && "${params.server}" == 'Prod2') {
                            echo "The script being executed next is ${params.script} in the ${params.environment} on the ${params.server} server."
                            node(label: 'Prod') {
                                git (
                                    [url: 'https://github.com/tylersul/jenkins-bax.git', 
                                    branch: 'master'])
                                script {
                                    powershell(". '.\\DeleteFiles.ps1'")
                                }
                            } 
                    }
                    if ("${params.environment}" == 'Prod' && "${params.server}" == 'Prod3') {
                            echo "The script being executed next is ${params.script} in the ${params.environment} on the ${params.server} server."
                            node(label: 'Prod') {
                                git (
                                    [url: 'https://github.com/tylersul/jenkins-bax.git', 
                                    branch: 'master'])
                                script {
                                    powershell(". '.\\DeleteFiles.ps1'")
                                }
                            } 
                    }
                }
            }
        }
    }
}



