properties([
    parameters([
        [$class: 'ChoiceParameter', 
            choiceType: 'PT_MULTI_SELECT', 
            description: 'Select the Env Name from the Dropdown List', 
            filterLength: 1, 
            filterable: false, 
            name: 'environment', 
            randomName: 'choice-parameter-5631314439613978', 
            script: [
                $class: 'GroovyScript', 
                fallbackScript: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        'return[\'Could not get Env\']'
                ], 
                script: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        'return["Dev","Test","Prod"]'
                ]
            ]
        ], 
        [$class: 'CascadeChoiceParameter', 
            choiceType: 'PT_MULTI_SELECT', 
            description: 'Select the Server from the Dropdown List', 
            filterLength: 1, 
            filterable: false, 
            name: 'server', 
            randomName: 'choice-parameter-5631314456178619', 
            referencedParameters: 'environment', 
            script: [
                $class: 'GroovyScript', 
                fallbackScript: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        'return[\'Could not get Environment from Env Param\']'
                ], 
                script: [
                    classpath: [], 
                    sandbox: false, 
                    script: 
                        ''' if (environment.equals("Dev")){
                                return["USOHCOGAPP901","APSGCOGAPP901","DEFRCOGAPP902"]
                            }
                            else if(environment.equals("Test")){
                                return["USOHCOGAPP901","APSGCOGAPP901","DEFRCOGAPP902"]
                            }
                            else if(environment.equals("Prod")){
                                return["USOHCOGAPP901","APSGCOGAPP901","DEFRCOGAPP902"]
                            }
                        '''
                ]
            ]
        ],

        choice(name: 'script',
        choices: 'DumpFileCleanup',
        description: 'Select script:'),

        choice(name: 'services',
        choices: 'DISP\nWEB',
        description: 'Select service:'),
        
    ])
])

def String[] serverGroup = "${params.server}".split(',');

// Create the pipeline
pipeline {
    // Allows pipeline to be run on any available agent
    agent any
    // Stages in build pipeline
    stages {
        // First stage in pipeline: review inputs and output to Jenkins console
        stage ('Parameter Validation') {
        // Steps in Parameter Validation stage
            steps {
                // Output parameters selected at time of build to Jenkins console
                echo '---------------------------------------------------------'
                echo "Checking environment input... selected: ${params.environment}"
                echo "Checking server input(s)... selected: ${params.server}"
                echo "Checking script input... selected: ${params.script}"
                echo "Checking directory input... selected: ${params.SourcePath}"
                echo '---------------------------------------------------------'
            }
        }
        // Second stage in pipeline: download script and execute on in-scope servers
        stage ('Execute Script') {
            steps {
                script {
                    // For Loop to utilize the serverGroup array 
                    for (x in serverGroup) { 
                        // Output each server to console with line for spacing
                        echo "$x ---------------------------------------------------------\n"

                        echo "The script being executed next is ${params.script} in the ${params.environment} on the $x server."
                        // Where the script will be executed
                        node(label: "Dev") {
                            // Checkout scripts from remote repo and download to Jenkins master 
                            git (
                                [url: 'https://github.com/tylersul/jenkins-bax.git', 
                                branch: 'master'])
                            // Execute script on servers
                            script {
                                powershell(". '.\\WebImages_V2.ps1'; WebImages -server $x -Services ${params.services}")
                            }
                        } 
                    }
                }
            }
        }
    }
}



